/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WellsIndexRouteImport } from './routes/wells/index'
import { Route as ReservoirsIndexRouteImport } from './routes/reservoirs/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as WellsIdRouteImport } from './routes/wells/$id'
import { Route as ReservoirsIdRouteImport } from './routes/reservoirs/$id'
import { Route as ProjectsIdRouteImport } from './routes/projects/$id'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WellsIndexRoute = WellsIndexRouteImport.update({
  id: '/wells/',
  path: '/wells/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservoirsIndexRoute = ReservoirsIndexRouteImport.update({
  id: '/reservoirs/',
  path: '/reservoirs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const WellsIdRoute = WellsIdRouteImport.update({
  id: '/wells/$id',
  path: '/wells/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservoirsIdRoute = ReservoirsIdRouteImport.update({
  id: '/reservoirs/$id',
  path: '/reservoirs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/reservoirs/$id': typeof ReservoirsIdRoute
  '/wells/$id': typeof WellsIdRoute
  '/projects': typeof ProjectsIndexRoute
  '/reservoirs': typeof ReservoirsIndexRoute
  '/wells': typeof WellsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/reservoirs/$id': typeof ReservoirsIdRoute
  '/wells/$id': typeof WellsIdRoute
  '/projects': typeof ProjectsIndexRoute
  '/reservoirs': typeof ReservoirsIndexRoute
  '/wells': typeof WellsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/reservoirs/$id': typeof ReservoirsIdRoute
  '/wells/$id': typeof WellsIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/reservoirs/': typeof ReservoirsIndexRoute
  '/wells/': typeof WellsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/projects/$id'
    | '/reservoirs/$id'
    | '/wells/$id'
    | '/projects'
    | '/reservoirs'
    | '/wells'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/projects/$id'
    | '/reservoirs/$id'
    | '/wells/$id'
    | '/projects'
    | '/reservoirs'
    | '/wells'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/projects/$id'
    | '/reservoirs/$id'
    | '/wells/$id'
    | '/projects/'
    | '/reservoirs/'
    | '/wells/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  ReservoirsIdRoute: typeof ReservoirsIdRoute
  WellsIdRoute: typeof WellsIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ReservoirsIndexRoute: typeof ReservoirsIndexRoute
  WellsIndexRoute: typeof WellsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wells/': {
      id: '/wells/'
      path: '/wells'
      fullPath: '/wells'
      preLoaderRoute: typeof WellsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservoirs/': {
      id: '/reservoirs/'
      path: '/reservoirs'
      fullPath: '/reservoirs'
      preLoaderRoute: typeof ReservoirsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wells/$id': {
      id: '/wells/$id'
      path: '/wells/$id'
      fullPath: '/wells/$id'
      preLoaderRoute: typeof WellsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservoirs/$id': {
      id: '/reservoirs/$id'
      path: '/reservoirs/$id'
      fullPath: '/reservoirs/$id'
      preLoaderRoute: typeof ReservoirsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  ReservoirsIdRoute: ReservoirsIdRoute,
  WellsIdRoute: WellsIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ReservoirsIndexRoute: ReservoirsIndexRoute,
  WellsIndexRoute: WellsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
